import Head from 'next/head'
import { ChangeEvent, useState } from 'react'
export default function Home() {
  const [file, setFile] = useState<File>()
  const [res, setRes] = useState<any>({})

  const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      setFile(e.target.files[0]);
    }
  };
  const handleUploadClick = () => {
    if (!file) {
      return;
    }
    const formData = new FormData();
    formData.append('image', file);
    fetch('https://api.imgbb.com/1/upload?key=b96681fa75ea775b33dc015c1a45ad81', {
      method: 'POST',
      body: formData,
    })
      .then((res) => res.json())
      .then((data) => {
        setRes(data.data);
      })
      .catch((err) => console.error(err));
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input onChange={handleFileChange} type="file" />

      <img style={{ height: "400px" }} src={res?.url} alt="upload" />

      <button onClick={handleUploadClick}>submit</button>
    </>
  )
}
